trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  credentials: 'aws-azure'
  region: 'us-east-1'
  helm-alb-uri: 'https://aws.github.io/eks-charts'
  helm-alb-version: '1.4.1'

steps:
  - checkout: self  

  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'

  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'sonar'
      scannerMode: 'Other'
      extraProperties: |
        # Additional properties that will be passed to the scanner, 
        # Put one key=value per line, example:
        # sonar.exclusions=**/*.bin
        sonar.projectKey=LeandroM27_MicroServicio_Evaluacion_3e6167fe-2365-463d-80b4-b24691b7c29b
        sonar.projectName=MicroServicio_Evaluacion

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify sonar:sonar'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest'

  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'

  - task: AWSShellScript@1
    displayName: 'CI'
    inputs:
      awsCredentials: $(credentials)
      regionName: $(region)
      failOnStandardError: true
      scriptType: 'inline'
      inlineScript: |
        echo 'Creating tag'
        tag=$(date '+%Y%m%d-%H%M')
        echo 'Building docker image'
        docker build -t $(REPO):${tag} .
        echo 'log in to ecr repo'
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 438555236323.dkr.ecr.us-east-1.amazonaws.com
        echo 'pushing image'
        docker push $(REPO):${tag}
  
